version: '3.3'

services:
  covid19-immunization-mediator:
    image: jembi/openhim-mediator-mapping:v2.3.0
    container_name: covid19-immunization-mediator
    environment:
      - OPENHIM_URL=https://core:8080
      - OPENHIM_USERNAME=root@openhim.org
      - OPENHIM_PASSWORD=instant101
      - MONGO_URL=mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/mapping-mediator?replicaSet=mongo-set
      - PARSER_LIMIT=10mb
      - MEDIATOR_URN=covid19-immunization-tracking-mediator
